# FL
# Shoulder or x
float32 fls
# Elbow or y
float32 fle
# Wrist or z
float32 flw

# FR
# Shoulder or x
float32 frs
# Elbow or y
float32 fre
# Wrist or z
float32 frw

# BL
# Shoulder or x
float32 bls
# Elbow or y
float32 ble
# Wrist or z
float32 blw

# BR
# Shoulder or x
float32 brs
# Elbow or y
float32 bre
# Wrist or z
float32 brw

# Move Type (for servo smoothness)
# step is 0
# view is 1
bool step_or_view