#!/usr/bin/env python
"""
DESCRIPTION:

SUBSCRIBERS:
"""

from __future__ import division
import os
import rospy
import numpy as np
from mini_ros.msg import MiniCmd, JoyButtons
from mini_ros.srv import CalibServo, CalibServoResponse
import copy

import sys

import rospkg
rospack = rospkg.RosPack()

sys.path.append(rospack.get_path('mini_ros') + '/../')

sys.path.append('../../')

from spot_real.Control.RPi.lib.Teensy_Interface import TeensyInterface


class ServoCalibrator():
    def __init__(self):

        rospy.init_node('ServoCalibrator', anonymous=True)
        self.TI = TeensyInterface()
        print("READY TO GO!")

        self.serv = rospy.Service('servo_calibrator', CalibServo,
                                  self.calib_service_cb)

    def calib_service_cb(self, req):
        """ Requests a servo to be moved to a certain position

            Args: req
            Returns: response
        """
        try:
            # 4 will indicate calibration request, 100 is servo speed
            self.TI.add_to_buffer(4, req.servo_num, req.servo_angle, 100)
            self.TI.send_buffer()
            response = "Servo Command Sent."
        except rospy.ROSInterruptException:
            response = "FAILED to send Servo Command"
        return CalibServoResponse(response)


def main():
    """ The main() function. """
    srv_calib = ServoCalibrator()
    rospy.loginfo("Use The servo_calibrator service.")
    while not rospy.is_shutdown():
        rospy.logdebug(srv_calib.TI.read_buffer())
        rospy.spin()


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass