#!/usr/bin/env python
"""
DESCRIPTION:

SUBSCRIBERS:
"""

from __future__ import division
import rospy
import numpy as np
from mini_ros.msg import MiniCmd, JoyButtons, IMUdata, ContactData, BezierData, JointAngles
import copy
import sys
import os
import rospkg
rospack = rospkg.RosPack()

sys.path.append(rospack.get_path('mini_ros') + '/../')

sys.path.append('../../')

from spotmicro.Kinematics.SpotKinematics import SpotModel
from spotmicro.GaitGenerator.Bezier import BezierGait
from spot_real.Control.RPi.lib.Teensy_Interface import TeensyInterface
from spot_bullet.src.ars_lib.ars import ARSAgent, Normalizer, Policy
from spotmicro.GymEnvs.spot_bezier_env import spotBezierEnv

# Controller Params
STEPLENGTH_SCALE = 0.06
Z_SCALE_CTRL = 0.12
RPY_SCALE = 0.6
SV_SCALE = 0.1
CHPD_SCALE = 0.0005
YAW_SCALE = 1.0

# AGENT PARAMS
CD_SCALE = 0.05
SLV_SCALE = 0.05
RESIDUALS_SCALE = 0.03
Z_SCALE = 0.05
# Filter actions
alpha = 0.7
# Added this to avoid filtering residuals
# -1 for all
actions_to_filter = 2


class SpotCommander():
    def __init__(self, Agent=False, contacts=False):

        rospy.init_node('Policies', anonymous=True)
        # self.movetypes = [
        #     "Forward", "Backward", "Left", "Right", "CW", "CCW", "Stop"
        # ]
        self.Agent = Agent
        self.movetypes = ["Stop"]
        self.mini_cmd = MiniCmd()
        self.jb = JoyButtons()
        self.mini_cmd.x_velocity = 0.0
        self.mini_cmd.y_velocity = 0.0
        self.mini_cmd.rate = 0.0
        self.mini_cmd.roll = 0.0
        self.mini_cmd.pitch = 0.0
        self.mini_cmd.yaw = 0.0
        self.mini_cmd.z = 0.0
        self.mini_cmd.motion = "Stop"
        self.mini_cmd.movement = "Stepping"
        # FIXED
        self.BaseStepVelocity = 0.1
        self.StepVelocity = self.BaseStepVelocity
        # Stock, use Bumpers to change
        self.BaseSwingPeriod = 0.2
        self.SwingPeriod = self.BaseSwingPeriod
        # Stock, use arrow pads to change
        self.BaseClearanceHeight = 0.04
        self.BasePenetrationDepth = 0.005
        self.ClearanceHeight = self.BaseClearanceHeight
        self.PenetrationDepth = self.BasePenetrationDepth

        # Time
        self.time = rospy.get_time()

        # Contacts: FL, FR, BL, BR
        self.contacts = [0, 0, 0, 0]

        # IMU: R, P, Ax, Ay, Az, Gx, Gy, Gz
        self.imu = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

        # Serial Talker
        self.TI = TeensyInterface()

        self.spot = SpotModel()

        self.T_bf0 = self.spot.WorldToFoot
        self.T_bf = copy.deepcopy(self.T_bf0)

        self.dt = 0.001

        self.bzg = BezierGait(dt=self.dt, Tswing=0.2)

        if self.Agent:
            self.load_spot(contacts)
        # cmd_cb from mini_cmd topic
        self.sub_cmd = rospy.Subscriber('mini_cmd', MiniCmd, self.cmd_cb)
        self.sub_jb = rospy.Subscriber('joybuttons', JoyButtons, self.jb_cb)
        self.sub_imu = rospy.Subscriber('spot/imu', IMUdata, self.imu_cb)
        self.sub_cnt = rospy.Subscriber('spot/contact', ContactData,
                                        self.cnt_cb)
        self.bez_pub = rospy.Publisher('spot/bezier', BezierData, queue_size=1)
        self.ja_pub = rospy.Publisher('spot/joints', JointAngles, queue_size=1)
        print("READY TO GO!")

    def load_spot(self, contacts):
        self.policy = Policy(state_dim=16, action_dim=15)
        self.normalizer = Normalizer(state_dim=16)
        env = spotBezierEnv(render=False,
                            on_rack=False,
                            height_field=False,
                            draw_foot_path=False)
        agent = ARSAgent(self.normalizer, self.policy, env)
        my_path = os.path.abspath(os.path.dirname(__file__))
        if contacts:
            models_path = os.path.join(my_path, "../models/contact")
        else:
            models_path = os.path.join(my_path, "../models/no_contact")
        agent_num = 149
        file_name = "spot_ars_"
        if os.path.exists(models_path + "/" + file_name + str(agent_num) +
                          "_policy"):
            print("Loading Existing agent")
            agent.load(models_path + "/" + file_name + str(agent_num))
            agent.policy.episode_steps = np.inf
            self.policy = agent.policy

        self.action = np.zeros(15)
        self.old_act = self.action[:actions_to_filter]

    def imu_cb(self, imu):
        """ Reads the IMU

            Args: imu
        """
        try:
            # Update imu
            self.imu = [
                imu.roll, imu.pitch, imu.gyro_x, imu.gyro_y, imu.gyro_z,
                imu.acc_x, imu.acc_y, imu.acc_z
            ]
            # log input data as debug-level message
            rospy.logdebug(imu)
        except rospy.ROSInterruptException:
            pass

    def cnt_cb(self, cnt):
        """ Reads the Contact Sensors

            Args: cnt
        """
        try:
            # Update contacts
            self.contacts = [cnt.FL, cnt.FR, cnt.BL, cnt.BR]
            # log input data as debug-level message
            rospy.logdebug(cnt)
        except rospy.ROSInterruptException:
            pass

    def cmd_cb(self, mini_cmd):
        """ Reads the desired Minitaur command and passes it for execution

            Args: mini_cmd
        """
        try:
            # Update mini_cmd
            self.mini_cmd = mini_cmd
            # log input data as debug-level message
            rospy.logdebug(mini_cmd)
        except rospy.ROSInterruptException:
            pass

    def jb_cb(self, jb):
        """ Reads the desired additional joystick buttons

            Args: jb
        """
        try:
            # Update jb
            self.jb = jb
            # log input data as debug-level message
            rospy.logdebug(jb)
        except rospy.ROSInterruptException:
            pass

    def move(self):
        """ Turn joystick inputs into commands
        """

        x_offset = -0.000
        z_offset = -0.02
        # x_offset = 0.0
        # z_offset = 0.0

        if self.mini_cmd.motion != "Stop":
            self.StepVelocity = self.BaseStepVelocity
            self.StepPeriod = np.clip(
                self.BaseSwingPeriod +
                (-self.mini_cmd.faster + -self.mini_cmd.slower) * SV_SCALE,
                0.1, 0.3)
            if self.mini_cmd.movement == "Stepping":
                StepLength = self.mini_cmd.x_velocity + abs(
                    self.mini_cmd.y_velocity * 0.66)
                StepLength = np.clip(StepLength, -1.0, 1.0)
                StepLength *= STEPLENGTH_SCALE
                LateralFraction = self.mini_cmd.y_velocity * np.pi / 2
                YawRate = self.mini_cmd.rate * YAW_SCALE
                # x offset
                pos = np.array(
                    [x_offset, 0.0, self.mini_cmd.z * Z_SCALE_CTRL + z_offset])
                orn = np.array([0.0, 0.0, 0.0])
            else:
                StepLength = 0.0
                LateralFraction = 0.0
                YawRate = 0.0
                # RESET
                self.ClearanceHeight = self.BaseClearanceHeight
                self.PenetrationDepth = self.BasePenetrationDepth
                self.StepVelocity = self.BaseStepVelocity
                # x offset
                pos = np.array(
                    [x_offset, 0.0, self.mini_cmd.z * Z_SCALE_CTRL + z_offset])
                orn = np.array([
                    self.mini_cmd.roll * RPY_SCALE,
                    self.mini_cmd.pitch * RPY_SCALE,
                    self.mini_cmd.yaw * RPY_SCALE
                ])
        else:
            StepLength = 0.0
            LateralFraction = 0.0
            YawRate = 0.0
            # RESET
            self.ClearanceHeight = self.BaseClearanceHeight
            self.PenetrationDepth = self.BasePenetrationDepth
            self.StepVelocity = self.BaseStepVelocity
            self.SwingPeriod = self.BaseSwingPeriod
            pos = np.array([x_offset, 0.0, z_offset])
            orn = np.array([0.0, 0.0, 0.0])

        # TODO: integrate into controller
        self.ClearanceHeight += self.jb.updown * CHPD_SCALE
        self.PenetrationDepth += self.jb.leftright * CHPD_SCALE

        # Manual Reset
        if self.jb.left_bump or self.jb.right_bump:
            self.ClearanceHeight = self.BaseClearanceHeight
            self.PenetrationDepth = self.BasePenetrationDepth
            self.StepVelocity = self.BaseStepVelocity
            self.SwingPeriod = self.BaseSwingPeriod

        # OPTIONAL: Agent
        if self.Agent:
            phases = copy.deepcopy(self.bzg.Phases)
            # Total 16
            state = []
            # r, p, gz, gy, gz, ax, ay, az (8)
            state.extend(self.imu)
            # FL, FR, BL, BR (4)
            state.extend(phases)
            # FL, FR, BL, BR (4)
            state.extend(self.contacts)
            self.normalizer.observe(state)
            # Don't normalize contacts
            state[:-4] = self.normalizer.normalize(state)[:-4]
            self.action = self.policy.evaluate(state, None, None)
            self.action = np.tanh(self.action)
            # EXP FILTER
            self.action[:actions_to_filter] = alpha * self.old_act + (
                1.0 - alpha) * self.action[:actions_to_filter]
            self.old_act = self.action[:actions_to_filter]

            self.ClearanceHeight += self.action[0] * CD_SCALE

        # Time
        dt = rospy.get_time() - self.time
        # print("dt: {}".format(dt))
        self.time = rospy.get_time()

        # Update Step Period
        self.bzg.Tswing = self.SwingPeriod

        self.T_bf = self.bzg.GenerateTrajectory(StepLength, LateralFraction,
                                                YawRate, self.StepVelocity,
                                                self.T_bf0, self.T_bf,
                                                self.ClearanceHeight,
                                                self.PenetrationDepth,
                                                self.contacts, dt)

        # OPTIONAL: Agent
        if self.Agent:
            # Add DELTA to XYZ Foot Poses
            self.T_bf["FL"][3, :3] += self.action[2:5] * RESIDUALS_SCALE
            self.T_bf["FR"][3, :3] += self.action[5:8] * RESIDUALS_SCALE
            self.T_bf["BL"][3, :3] += self.action[8:11] * RESIDUALS_SCALE
            self.T_bf["BR"][3, :3] += self.action[11:14] * RESIDUALS_SCALE
            pos[2] += self.action[1] * Z_SCALE

        joint_angles = self.spot.IK(orn, pos, self.T_bf)

        ja_msg = JointAngles()

        ja_msg.fls = np.degrees(joint_angles[0][0])
        ja_msg.fle = np.degrees(joint_angles[0][1])
        ja_msg.flw = np.degrees(joint_angles[0][2])

        ja_msg.frs = np.degrees(joint_angles[1][0])
        ja_msg.fre = np.degrees(joint_angles[1][1])
        ja_msg.frw = np.degrees(joint_angles[1][2])

        ja_msg.bls = np.degrees(joint_angles[2][0])
        ja_msg.ble = np.degrees(joint_angles[2][1])
        ja_msg.blw = np.degrees(joint_angles[2][2])

        ja_msg.brs = np.degrees(joint_angles[3][0])
        ja_msg.bre = np.degrees(joint_angles[3][1])
        ja_msg.brw = np.degrees(joint_angles[3][2])

        self.ja_pub.publish(ja_msg)

        # for i in range(len(joint_angles)):
        #     # NOTE: Rounding to one decimal point or teensy can't read!
        #     # shoulder
        #     x = round(np.degrees(joint_angles[i][0]), 1)
        #     # elbow
        #     y = round(np.degrees(joint_angles[i][1]), 1)
        #     # wrist
        #     z = round(np.degrees(joint_angles[i][2]), 1)

        #     bzd = BezierData()

        #     bzd.Leg = str(i)
        #     bzd.x = x
        #     bzd.y = y
        #     bzd.z = z

        #     self.bez_pub.publish(bzd)


def main():
    """ The main() function. """
    mini_commander = SpotCommander()
    rate = rospy.Rate(600.0)
    while not rospy.is_shutdown():
        # This is called continuously. Has timeout functionality too
        mini_commander.move()
        rate.sleep()
        # rospy.spin()


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass